image: gossiemcschreck/ldwas-ci

clone:
    depth: full
pipelines:
    default:
        - step:
            caches:
                - maven
            script:
                - mvn -B verify -Pci
    branches:
        master:
            - step:
                caches:
                    - maven
                script:
                    - mvn -B verify -Pci
                    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
