image: maven:3.3.9

clone:
    depth: full
pipelines:
    default:
        -step:
            caches:
                - maven
            script:
                - mvn -B verify
    branches:
        master:
            - step:
                caches:
                    - maven
                script:
                    - mvn -B verify
                    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
