version: 2
jobs:
  build:
    docker:
      - image: gossiemcschreck/ldwas-ci:2.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn -B install -Pci
      - run: java -jar app/target/plan-app-0.0.1-SNAPSHOT.jar &
      - run: npm run --prefix web/src/main/web/ update:webdriver
      - run: npm run --prefix web/src/main/web/ e2e:ci
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

  deploy:
    docker:
      - image: gossiemcschreck/ldwas-ci:2.0
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - deploy:
          filters:
            branches:
              only: master
