version: 2
jobs:
  build:
    docker:
      - image: gossiemcschreck/ldwas-ci:latest

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx4096m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn -B install -Pci:test
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          background: true
          command: |
            docker-compose up --build --remove-orphans --detach
      - run: mvn -B -fweb install -Pci:e2e
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

  deploy:
    docker:
      - image: gossiemcschreck/ldwas-ci:latest
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - deploy:
          filters:
            branches:
              only: master
