version: 2
jobs:
  build:
    docker:
      - image: gossiemcschreck/ldwas-ci:1.3

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx4096m

    steps:
      - checkout

      #- restore_cache:
      #    keys:
      #      - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
      #      - v1-dependencies-

      - run: mvn -B install -Ptest:ci
      - run:
          background: true
          command: |
            java -jar app/target/plan-app-0.0.1-SNAPSHOT.jar
      - run: mvn -B -fweb install -Pe2e:ci
 #     - run: mvn dependency:go-offline

      #- save_cache:
      #    paths:
      #      - ~/.m2
      #    key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build:
    jobs:
      - build
