version: 2
jobs:
    build:
        docker:
            - image: gossiemcschreck/ldwas-ci:1.2

        working_directory: ~/repo

        environment:
            MAVEN_OPTS: -Xmx4096m

        steps:
            - checkout

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "pom.xml" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-

            - run: mvn -B verify -Pci:test
            - run:
                background: true
                command: |
                    rabbitmq-server -detached
            - run:
                background: true
                command: |
                    java -jar shopping-list/shopping-list-app/target/shopping-list-app-0.0.1-SNAPSHOT.jar
            - run:
                background: true
                command: |
                    java -jar cleaning-plan/cleaning-plan-app/target/cleaning-plan-app-0.0.1-SNAPSHOT.jar
            - run:
                background: true
                command: |
                    java -jar food-plan/food-plan-app/target/food-plan-app-0.0.1-SNAPSHOT.jar
            - run:
                background: true
                command: |
                    java -jar cookbook/cookbook-app/target/cookbook-app-0.0.1-SNAPSHOT.jar
            - run:
                background: true
                command: |
                    java -jar gateway/target/gateway-app-0.0.1-SNAPSHOT.jar
            - run: mvn -B -ffrontend verify -Pci:e2e
            - run: mvn dependency:go-offline

            - save_cache:
                paths:
                    - ~/.m2
                key: v1-dependencies-{{ checksum "pom.xml" }}

    deploy:
        docker:
            - image: gossiemcschreck/ldwas-ci:1.2
        steps:
            - checkout
            #- run:
            #    name: Deploy Master to Heroku
            #    command: |
            #        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
    version: 2
    build-deploy:
        jobs:
            - build:
                filters:
                    branches:
                        ignore:
                            - master
            - deploy:
                filters:
                    branches:
                        only: master
