spring:
    application:
        name: user
    datasource:
        url: jdbc:h2:mem:testdb

logging:
    level:
        org.springframework.web: ERROR
        org.hibernate: ERROR

server:
    port: ${PORT:8086}
