spring:
    datasource:
        url: jdbc:h2:mem:testdb
    freemarker:
        template-loader-path: classpath:/templates
        suffix: .html

logging:
    level:
        org.springframework.web: ERROR
        org.hibernate: ERROR

server:
    port: ${PORT:8080}
