spring:
    zipkin:
        baseUrl: http://zipkin:9411/
    sleuth:
        sampler:
            probability: 1.0
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: ${JDBC_DATABASE_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    cloud:
        stream:
            bindings:
                deletionInput:
                    destination: household_deletion
                    binder: local_rabbit
            binders:
                local_rabbit:
                    type: rabbit
                    environment:
                        spring:
                            rabbitmq:
                                host: ${RABBIT_MQ_HOST}
                                port: ${RABBIT_MQ_PORT}
                                username: ${RABBIT_MQ_USERNAME}
                                password: ${RABBIT_MQ_PASSWORD}

security:
    oauth2:
        client:
            clientId: bd1c0a783ccdd1c9b9e4
            clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
            accessTokenUri: http://user:8086/login/oauth/access_token
            userAuthorizationUri: http://user:8086/login/oauth/authorize
            clientAuthenticationScheme: form
        resource:
            userInfoUri: http://user:8086/user
            preferTokenInfo: false

sample:
    zipkin:
        enabled: true

shopping-list:
    url: http://shopping-list:8081

cleaning-plan:
    url: http://cleaning-plan:8082

food-plan:
    url: http://food-plan:8083

cookbook:
    url: http://cookbook:8084

household:
    url: http://household:8085

user:
    url: http://user:8086
