spring:
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: ${JDBC_DATABASE_URL:jdbc:h2:mem:testdb}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    cloud:
        stream:
            bindings:
                producer:
                    destination: household
                    binder: local_rabbit
                consumer:
                    destination: household
                    binder: local_rabbit
            binders:
                local_rabbit:
                    type: rabbit
                    environment:
                        spring:
                            rabbitmq:
                                host: ${RABBIT_MQ_HOST}
                                port: ${RABBIT_MQ_PORT}
                                username: ${RABBIT_MQ_USERNAME}
                                password: ${RABBIT_MQ_PASSWORD}
    freemarker:
        template-loader-path: classpath:/templates
        suffix: .html

logging:
    level:
        org.springframework.web: ERROR
        org.hibernate: ERROR

server:
    port: ${PORT:8080}
